service: boyyah-alexa-skill

provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

plugins:
  - serverless-dotenv-plugin
  - serverless-alexa-skills
  - serverless-python-requirements

functions:
  blood-pressure:
    handler: handler.handler
    events:
      - alexaSkill: ${env:ALEXA_SKILL_ID}
custom:
  pythonRequirements:
    usePipenv: true
  alexa:
    vendorId: ${env:AMAZON_VENDOR_ID}
    clientId: ${env:AMAZON_CLIENT_ID}
    clientSecret: ${env:AMAZON_CLIENT_SECRET}
    localServerPort: ${env:SEVER_PORT}
    skills:
      - id: ${env:ALEXA_SKILL_ID}
        skillManifest:
          publishingInformation:
            locales:
              en-GB:
                name: boyyah
          apis:
            custom:
              endpoint:
                uri: { Fn::GetAtt: [boyyah, Arn] }
          manifestVersion: "1.0"
        models:
          en-GB:
            interactionModel:
              languageModel:
                invocationName: boy yah
                intents:
                  - name: AMAZON.CancelIntent
                    samples: []
                  - name: AMAZON.HelpIntent
                    samples: []
                  - name: AMAZON.StopIntent
                    samples: []
                  - name: AMAZON.ResumeIntent
                    samples: []
                  - name: AMAZON.PauseIntent
                    samples: []
                  - name: AMAZON.YesIntent
                    samples: []
                  - name: StoreBloodPressure
                    slots:
                      - name: systolic_number
                        type: AMAZON.NUMBER
                      - name: diastolic_number
                        type: AMAZON.NUMBER
                    samples:
                      - "store my blood pressure {systolic_number} over {diastolic_number}"
                  - name: StorePeakFlowRate
                    slots:
                      - name: peak_flow_rate
                        type: AMAZON.NUMBER
                    samples:
                      - "store my peak flow rate {peak_flow_rate}"
                  - name: SendToDoctor
                    samples:
                      - "send my details to my doctor"
                      - "send to doctor"
                  - name: BloodPressureReading
                    slots:
                      - name: systolic_number
                        type: AMAZON.NUMBER
                      - name: diastolic_number
                        type: AMAZON.NUMBER
                    samples:
                      - "{systolic_number} over {diastolic_number}"
                      - "it's {systolic_number} over {diastolic_number}"
